services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sushantsur23/futuristic-wellness:latest
    container_name: futuristic_wellness
    ports:
      - "8000:80"
      - "80:80"
    environment:
      DATABASE_URL: "sqlite+aiosqlite:////app/backend/wellness.db"
      JWT_SECRET: "wellness_super_secret_session_key_1234567890_abc"
      ACCESS_TOKEN_EXPIRE_MINUTES: "10080"
    volumes:
      - uploads_data:/app/static/uploads
      - db_data:/app/backend
    restart: unless-stopped

volumes:
  uploads_data:
  db_data:
